### ISSUE TITLE
Can you explain the box model in CSS?

### ISSUE THREAD

**Issue by geekelo** [geekelo/dsa_practice#40]
Sure! The box model in CSS is a fundamental concept that describes how elements on a web page are structured and how they interact with each other. It consists of four main components:

1. **Content**: This is the innermost part of the box where the actual content (text, images, etc.) is displayed.

2. **Padding**: The space between the content and the border. Padding clears an area around the content, which can be set individually for each side (top, right, bottom, left).

3. **Border**: A line surrounding the padding (if any) and content. The border can be styled with different widths, colors, and styles (solid, dashed, etc.).

4. **Margin**: The outermost part of the box, creating space between the element and other elements on the page. Like padding, margins can be set individually for each side.

Here’s a visual representation of the box model:

```
+-----------------------+
|       Margin          |
|  +------------------+ |
|  |     Border       | |
|  | +--------------+ | |
|  | |   Padding    | | |
|  | | +----------+ | | |
|  | | |  Content | | | |
|  | | +----------+ | | |
|  | +--------------+ | |
|  +------------------+ |
+-----------------------+
```

### CSS Properties
Each component of the box model can be controlled using specific CSS properties:

- **Content**: The width and height properties.
- **Padding**: padding-top, padding-right, padding-bottom, padding-left, or shorthand padding.
- **Border**: border-width, border-style, border-color, or shorthand border.
- **Margin**: margin-top, margin-right, margin-bottom, margin-left, or shorthand margin.

### Example
Here's an example of how to style an element using the box model:

```css
.box {
  width: 200px;              /* Content width */
  height: 100px;             /* Content height */
  padding: 20px;             /* Padding */
  border: 5px solid black;   /* Border */
  margin: 10px;              /* Margin */
}
```

In this example:
- The content area is 200px by 100px.
- Padding adds 20px space inside the border around the content.
- The border is 5px thick and solid black.
- Margin adds 10px space outside the border, separating it from other elements.

### Box-Sizing Property
By default, the width and height properties only include the content area. To include padding and border in the width and height calculations, you can use the `box-sizing` property:

```css
.box {
  box-sizing: border-box;
}
```

With `box-sizing: border-box;`, the total width and height of the element will include padding and border, making it easier to manage the overall size of the element.
